export const Z1_TABLE_GROUPS = [
  {
    name: 'Technical',
    tables: [
      { key: 'tech_indicator', label: 'Technical indicators' },
      { key: 'market_regime', label: 'Market regime' },
    ],
  },
  {
    name: 'Perpetuals',
    tables: [{ key: 'perp_metric', label: 'Perp metrics' }],
  },
  {
    name: 'Macro + News',
    tables: [
      { key: 'macro_snapshot', label: 'Macro snapshot' },
      { key: 'news_embedding', label: 'News embedding' },
    ],
  },
  {
    name: 'Graph',
    tables: [{ key: 'asset_corr', label: 'Asset correlation' }],
  },
] as const;

export const Z1_COLUMN_HEADER_MAP: Record<string, string> = {
  FROM_SYMBOL: 'From symbol',
  TO_SYMBOL: 'To symbol',
  LOOKBACK_DAYS: 'Lookback days',
  CALC_DATE: 'Calc date',
  CORRELATION: 'Correlation',
  CONFIDENCE: 'Confidence',
  DATA_POINTS: 'Data points',
  SYMBOL: 'Symbol',
  TIMEFRAME: 'Timeframe',
  CANDLE_TIME: 'Candle time',
  CALCULATED_AT: 'Calculated at',
  SOURCE: 'Source',
  CLOSE_PRICE: 'Close',
  PRICE_CHANGE_PCT: 'Price change %',
  RANGE_PCT: 'Range %',
  BODY_RATIO: 'Body ratio',
  VOLUME: 'Volume',
  RSI_14: 'RSI 14',
  RSI_STATE: 'RSI state',
  MACD_LINE: 'MACD line',
  MACD_SIGNAL: 'MACD signal',
  MACD_HIST: 'MACD hist',
  MACD_CROSS: 'MACD cross',
  ATR_14: 'ATR 14',
  ATR_20D_AVG: 'ATR 20d avg',
  ATR_RATIO: 'ATR ratio',
  ATR_STATE: 'ATR state',
  EMA_20: 'EMA 20',
  EMA_50: 'EMA 50',
  EMA_200: 'EMA 200',
  EMA_ALIGNMENT: 'EMA alignment',
  BB_UPPER: 'BB upper',
  BB_MIDDLE: 'BB middle',
  BB_LOWER: 'BB lower',
  BB_WIDTH: 'BB width',
  BB_POSITION: 'BB position',
  VOLUME_SMA_20: 'Volume SMA 20',
  VOLUME_RATIO: 'Volume ratio',
  BUCKET_TIME: 'Bucket time',
  FUNDING_RATE: 'Funding rate',
  FUNDING_8H_AVG: 'Funding 8h avg',
  FUNDING_STATE: 'Funding state',
  OI_VALUE: 'OI value',
  OI_CHANGE_4H: 'OI change 4h',
  OI_CHANGE_1D: 'OI change 1d',
  OI_PRICE_DIVERGENCE: 'OI/price divergence',
  LIQUIDATION_LONG_SUM: 'Long liquidation',
  LIQUIDATION_SHORT_SUM: 'Short liquidation',
  LIQUIDATION_IMBALANCE: 'Liquidation imbalance',
  LS_RATIO_TOP: 'Top L/S',
  LS_RATIO_GLOBAL: 'Global L/S',
  LS_DIVERGENCE: 'L/S divergence',
  SUPPLY_PRESSURE: 'Supply pressure',
  SNAPSHOT_DATE: 'Snapshot date',
  US10Y_YIELD: 'US 10Y',
  US2Y_YIELD: 'US 2Y',
  YIELD_SPREAD: 'Yield spread',
  YIELD_CURVE_STATE: 'Yield curve',
  FED_FUNDS_RATE: 'Fed funds rate',
  DXY_VALUE: 'DXY',
  DXY_CHANGE_1W: 'DXY 1w change',
  DXY_STATE: 'DXY state',
  VIX_VALUE: 'VIX',
  VIX_STATE: 'VIX state',
  GOLD_VALUE: 'Gold',
  SPX_CHANGE_1W: 'SPX 1w change',
  M2_CHANGE_3M: 'M2 3m change',
  LIQUIDITY_STATE: 'Liquidity state',
  BTC_DOMINANCE: 'BTC dominance',
  BTC_DOM_CHANGE_1W: 'BTC dom 1w',
  STABLECOIN_MCAP_CHANGE_1W: 'Stablecoin mcap 1w',
  STABLECOIN_FLOW_STATE: 'Stablecoin flow',
  LATEST_EVENT_NAME: 'Latest event',
  LATEST_EVENT_SURPRISE: 'Latest surprise',
  NEXT_EVENT_NAME: 'Next event',
  NEXT_EVENT_DATE: 'Next event date',
  DAYS_TO_NEXT_EVENT: 'Days to next event',
  MACRO_REGIME: 'Macro regime',
  EMBEDDING_ID: 'Embedding ID',
  ARTICLE_ID: 'Article ID',
  CHUNK_TEXT: 'Chunk text',
  SENTIMENT_SCORE: 'Sentiment score',
  SENTIMENT_LABEL: 'Sentiment label',
  KEY_TOPICS: 'Key topics',
  RELEVANCE_SCORE: 'Relevance score',
  PUBLISHED_AT: 'Published at',
  REGIME: 'Regime',
  REGIME_SCORE: 'Regime score',
  TREND_DIRECTION: 'Trend direction',
  TREND_STRENGTH: 'Trend strength',
  VOLATILITY_STATE: 'Volatility',
  MOMENTUM_STATE: 'Momentum',
  SUPPORT_LEVELS: 'Support levels',
  RESISTANCE_LEVELS: 'Resistance levels',
  REGIME_FACTORS: 'Regime factors',
};

export const Z1_ENUM_VALUE_MAP: Record<string, Record<string, string>> = {
  RSI_STATE: { OVERSOLD: 'Oversold', NEUTRAL: 'Neutral', OVERBOUGHT: 'Overbought' },
  EMA_ALIGNMENT: { BULLISH: 'Bullish', BEARISH: 'Bearish', MIXED: 'Mixed' },
  MACD_CROSS: { GOLDEN: 'Golden', DEAD: 'Dead', NONE: 'None' },
  FUNDING_STATE: {
    STRONG_LONG: 'Strong long',
    LONG: 'Long',
    NEUTRAL: 'Neutral',
    SHORT: 'Short',
    STRONG_SHORT: 'Strong short',
  },
  OI_PRICE_DIVERGENCE: { CONFIRMING: 'Confirming', DIVERGING: 'Diverging', NEUTRAL: 'Neutral' },
  LS_DIVERGENCE: { ALIGNED: 'Aligned', DIVERGING: 'Diverging' },
  SUPPLY_PRESSURE: { BULLISH: 'Bullish', NEUTRAL: 'Neutral', BEARISH: 'Bearish' },
  YIELD_CURVE_STATE: { NORMAL: 'Normal', FLAT: 'Flat', INVERTED: 'Inverted', UNKNOWN: 'Unknown' },
  DXY_STATE: { STRENGTHENING: 'Strengthening', STABLE: 'Stable', WEAKENING: 'Weakening' },
  VIX_STATE: { LOW: 'Low', NORMAL: 'Normal', HIGH: 'High', EXTREME: 'Extreme', UNKNOWN: 'Unknown' },
  LIQUIDITY_STATE: { EXPANDING: 'Expanding', STABLE: 'Stable', CONTRACTING: 'Contracting' },
  STABLECOIN_FLOW_STATE: { INFLOW: 'Inflow', STABLE: 'Stable', OUTFLOW: 'Outflow' },
  MACRO_REGIME: { RISK_ON: 'Risk on', NEUTRAL: 'Neutral', RISK_OFF: 'Risk off' },
  REGIME: {
    STRONG_UPTREND: 'Strong uptrend',
    UPTREND: 'Uptrend',
    RANGE_BOUND: 'Range bound',
    DOWNTREND: 'Downtrend',
    STRONG_DOWNTREND: 'Strong downtrend',
  },
  TREND_DIRECTION: { UP: 'Up', DOWN: 'Down', FLAT: 'Flat' },
  TREND_STRENGTH: { STRONG: 'Strong', MODERATE: 'Moderate', WEAK: 'Weak' },
  VOLATILITY_STATE: { LOW: 'Low', NORMAL: 'Normal', HIGH: 'High', EXTREME: 'Extreme' },
  MOMENTUM_STATE: {
    ACCELERATING: 'Accelerating',
    STABLE: 'Stable',
    DECELERATING: 'Decelerating',
    REVERSING: 'Reversing',
  },
  SENTIMENT_LABEL: {
    VERY_BEARISH: 'Very bearish',
    BEARISH: 'Bearish',
    NEUTRAL: 'Neutral',
    BULLISH: 'Bullish',
    VERY_BULLISH: 'Very bullish',
  },
};
